name = "KMeanClusttering"
uuid = "ba027c65-82f8-50c6-84cc-e563f848bce6"
authors = ["josePereiro <jose.pereiro.lab@gmail.com>"]
version = "0.1.0"

[deps]
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
UnicodePlots = "b8865327-cd53-5732-bb35-84acbb429228"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
